config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pages#home' #creates root_path
  get "about" => "pages#about" #creates about_path
  get "search" => "pages#search"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :words]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = Pin.new
  end

  def edit
  end

  def create
    @pin = Pin.new(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<nav class='footer' role='navigation'>
	<div id='swiftype'>
		<a class='btn btn-default btn-lg' id='st-input-powered-by' href="https://swiftype.com">
		  <img src='assets/powered-by-swiftype.png' alt="Powered by Swiftype">
    </a>
	</div>
	<div id='mixpanel'>
		<a href="https://mixpanel.com/f/partner">
			<img src="//cdn.mxpnl.com/site_media/images/partner/badge_blue.png" alt="Mobile Analytics" />
		</a>
	</div>
</nav>
<!-- Google Sitelinks Search Box -->
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "WebSite",
        "url": "http://alec-pinteresting.com",
        "potentialAction": {
          "@type": "SearchAction",
          "target": "http://alec-pinteresting.com/#stq={query}",
          "query-input": "required name=query"
        }
      }
    </script>

    <!-- Invisible link to G+. Because SEO. -->
    <a href="https://plus.google.com/+AlecWilson" rel="publisher"></a>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Pins", pins_path, method: :delete %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
      
      <!-- Adds Swiftype Search not using simple overlay -->
      <!-- To change configuration, use Swiftype install dashboard-->
        <li itemscope itemtype="http://schema.org/WebSite">
          <meta itemprop="url" content="http://alec-pinteresting.com"/>
          <form itemprop="potentialAction" itemscope itemtype="http://schema.org/SearchAction">
            <meta itemprop="target" content="http://alec-pinteresting.com/#stq={query}"/>
            <input itemprop="query-input" type="text" id="st-search-input" class="st-search-input" name="query"/>
          </form>    

      <!-- Adds Swiftype Search -->
      <script type="text/javascript">
        (function(w,d,t,u,n,s,e){w['SwiftypeObject']=n;w[n]=w[n]||function(){
        (w[n].q=w[n].q||[]).push(arguments);};s=d.createElement(t);
        e=d.getElementsByTagName(t)[0];s.async=1;s.src=u;e.parentNode.insertBefore(s,e);
        })(window,document,'script','//s.swiftypecdn.com/install/v1/st.js','_st');

        _st('install','A3sx3pw-UyZUSoWYsh7s');
      </script></li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head> <%# Applies to entire application - pages are loaded within this %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <meta name="viewport" content="width:100%">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Pinteresting</title>
  <meta property="st:title" content="Pinteresting"/>
  <meta name="viewport" content="width=1024">
  <meta property="og:url" content="http://alec-pinteresting.com/"/>
  <meta property="og:site_name" content="Alec Pinteresting"/>
  <meta property="og:title" content="Alec Pinteresting"/>
  <meta property="og:description" content="This is my One Month Rails Pinteresting site.">
  <meta name="twitter:description" content="This is my One Month Rails Pinteresting site.">
  <meta name="twitter:title" content="Alec Pinteresting">
  <meta name="description" content="This is my One Month Rails Pinteresting site.">
  <meta name="twitter:creator" content="@alecfwilson">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' =>	true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="canonical" href="http://alec-pinteresting.com/" />
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
  <link rel="icon" href="/favicon_32.png" sizes="32x32">
  <link rel="icon" href="/favicon_64.png" sizes="64x64">
  <!-- Bing Webmaster Verification -->
  <meta name="msvalidate.01" content="1EB9017CD4DBDBA2DAEFB33D189D1691" />
  <!-- facebook insights -->
  <meta property="fb:admins" content="1065810113" />
  <!-- start GA -->   
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-56821263-1', 'auto');
    ga('require', 'linkid', 'linkid.js');
    ga('require', 'displayfeatures');
    ga('send', 'pageview');

    </script>
  <!-- end GA -->
  <!-- start Mixpanel -->
    <script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
    for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
    mixpanel.init("e89b03345bda892c4d8c6613a27a1358");</script>
  <!-- end Mixpanel -->
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About This Project</h1>
<div itemscope itemtype="http://schema.org/Person">
  <p>My name is <span itemprop="name givenName"><link itemprop="sameAs" href="https://www.freebase.com/m/011tx8q2"><link itemprop="sameAs" href="http://www.crunchbase.com/person/alec-wilson"><link itemprop="sameAs" href="https://angel.co/alecfwilson">Alec Wilson</span>. During the day, I work as the <span itemprop="jobTitle">Director of Growth</span> at <span itemprop="worksFor"><a href="https://swiftype.com"><link itemprop="sameAs" href="http://en.wikipedia.org/wiki/Swiftype"><link itemprop="sameAs" href="https://www.freebase.com/m/0114y0fk"><link itemprop="sameAs" href="http://www.crunchbase.com/organization/swiftype"><link itemprop="sameAs" href="https://angel.co/swiftype">Swiftype</a></span> in <span itemscope="workLocation">San Francisco</span>. You can get the best search experience for your website <span itemscope="makesOffer"><a href="https://swiftype.com/pricing">here</a>.</span></p>
<div itemscope itemtype="http://schema.org/Thing">
	<p>This is my in progress <span itemscope="name">One Month Rails Pinteresting app</span></div></div></p>

app/views/pages/home.html.erb
<div class="jumbotron center">
 <h1>ASPIRATIONAL WORDS</h2>
  <p>Reload the page for a random aspirational word<p>
 <% if user_signed_in? %>
      <p><%= ['relax','observe','analyze','learn'].sample %></p>
      <%= link_to "Pins", pins_path, class: "btn btn-primary btn-lg" %>
 <% else %>
   <p><%= ['relax','observe','analyze','learn'].sample %></p>

   <p>
     <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
     <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
   </p>
  <% end %>  
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
        <tr>
          <td class="btn btn-default btn-sm pin"><%= pin.description %></td>
          <td><%= link_to 'Show', pin, class: "btn btn-primary btn-xs crud" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-primary btn-xs crud" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= link_to 'Destroy', pin, class: "btn btn-primary btn-xs crud", method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path, class: "btn btn-primary" %>
<br>
<br>
<Strong>ASPIRATIONAL WORDS</strong>
  <p>Click the button for a random word, chosen from your pins<p>
<p><%= link_to @pins.sample.description, pins_path, class: "btn btn-primary btn-lg" %></p>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>